Feature/save static resources
mithunkoppal/vaxerch pull request #11
Opened 2021-05-08 19:37 UTC by ankurdh

states and districts information is very less likely to change. Might be
useful to just download them once and for all and save them on the
filesystem alongside the repo to reuse.

The change adds a script to download the states and the districts jsons
and save locally. And also adds the States, MH and Kar state districts
jsons to the filesystem.

2021-05-08 21:16 UTC, mithunkoppal requested changes
please check my comments

2021-05-08 21:16 UTC, mithunkoppal commented on cowin_api/vaccine_avail_elder.py
>  bot = telegram_chatbot("config_blr.cfg")
Can you please add cowin_api/config_blr.cfg instead of config_blr.cfg. Since I had all my required files in the same directory I never needed to mentioned the parent directory?
You can make this change in all .py files where we are running our business logic.

2021-05-08 21:16 UTC, mithunkoppal commented on cowin_api/vaxerch_bom_master.py
>                  validate_message_and_send('latest_message_bom.txt', 'temp_bom.txt', lock_bom, value)
Can you please add cowin_api/latest_message_bom.txt and  cowin_api/temp_bom.txt instead of filename.txt. Since I had all my required files in the same directory I never needed to mentioned the parent directory?
You can make this change in all .py files where we are running our business logic.

2021-05-08 21:16 UTC, mithunkoppal commented on ops/get_static_resources.py
> +        with open(f'resources/{res.STATES.value["filename"]}', 'w') as f:
you can remove 'resources' string from here because the filename already has resources

2021-05-08 21:19 UTC, ankurdh commented on ops/get_static_resources.py
> +        with open(f'resources/{res.STATES.value["filename"]}', 'w') as f:
Good Catch. Will fix it

2021-05-08 21:20 UTC, mithunkoppal commented
Please add 'ops' to setup.py so that it is installed as a module when someone runs pip3 install.

`packages=['cowin_api','ops']`

2021-05-08 21:26 UTC, ankurdh commented
> Please add 'ops' to setup.py so that it is installed as a module when someone runs pip3 install.
> 
> `packages=['cowin_api','ops']`

Hmm.. I'd rather not have people install it because it's just an ops thing and a consumer would typically not need this. Let me know if you think someone must have this script

2021-05-08 21:28 UTC, mithunkoppal commented
> > Please add 'ops' to setup.py so that it is installed as a module when someone runs pip3 install.
> > `packages=['cowin_api','ops']`
> 
> Hmm.. I'd rather not have people install it because it's just an ops thing and a consumer would typically not need this. Let me know if you think someone must have this script

Makes sense

2021-05-09 08:44 UTC, mithunkoppal approved these changes

2021-05-09 08:44 UTC, merged